# Generated by Django 2.1.4 on 2018-12-25 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('realName', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.IntegerField(default=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('tel', models.TextField(verbose_name='电话')),
                ('address', models.TextField(verbose_name='地址')),
                ('kindergarten', models.CharField(max_length=20)),
                ('primarySchool', models.CharField(max_length=20)),
                ('junior', models.CharField(max_length=20)),
                ('senior', models.CharField(max_length=20)),
                ('others', models.TextField(verbose_name='备注家长信息')),
                ('status', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('show', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('superManager', models.IntegerField(default=1)),
                ('show', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Manager'),
        ),
    ]
