# Generated by Django 2.1.4 on 2018-12-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='subject',
            field=models.CharField(default='科学', max_length=20, verbose_name='学科'),
        ),
    ]
