# Generated by Django 2.1.4 on 2018-12-27 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_worker_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuidName', models.CharField(max_length=20, unique=True, verbose_name='单号')),
                ('date', models.DateField(verbose_name='日期')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('money', models.FloatField(verbose_name='金额')),
                ('voucher', models.CharField(max_length=50, verbose_name='凭证')),
                ('others', models.TextField(verbose_name='备注')),
                ('status', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('addTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('show', models.IntegerField(default=1)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Manager')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Worker')),
            ],
        ),
    ]
